name: HAT-S_SRx4_Patch-Mosaic
model_type: HATModel
scale: 4
num_gpu: 1
manual_seed: 0
is_train: False
dist: False


# network structures
network_g:
  type: HAT
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 24
  squeeze_factor: 24
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 144
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: pretrained_models/HAT-S_SRx4_Patch-Mosaic.pth
  strict_load_g: false